# Generated by Django 4.2.7 on 2023-11-17 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_profiles'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-date_uploaded',)},
        ),
    ]
